version: '3'

services:
  db:
    image: mongo:5
    restart: always
    container_name: petsDB
    ports:
     - 27017:27017
    environment:
     - DB_USER={$DB_USER}
     - DB_NAME={$DB_NAME}
     - DB_PASSWORD={$DB_PASSWORD}
    volumes:
     - ./data:/db/data
